### ISSUE TITLE
NoSuchMethodError updating when on master using sbt 0.13 

### ISSUE THREAD

**Issue by raboof** [typesafehub/sbt-whitesource#20]
When I check out master and do `sbt publishLocal`, then try to do a `whitesourceUpdate` in my project, I get a `NoSuchMethodError`

This is all still with sbt 0.13:

```
[info] Service URL is https://saas.whitesourcesoftware.com/agent
[info] Initiated WhiteSource Service
[info] Processing com.typesafe.akka:akka-camel:2.5-SNAPSHOT
[trace] Stack trace suppressed: run last akka/*:whitesourceUpdate for the full output.
[error] (akka/*:whitesourceUpdate) java.lang.NoSuchMethodError: sbt.librarymanagement.package$.RichUpdateReport(Lsbt/UpdateReport;)Lsbt/UpdateReport;
[error] Total time: 1 s, completed Aug 17, 2017 2:18:04 PM
akka > last akka/*:whitesourceUpdate
[info] Service URL is https://saas.whitesourcesoftware.com/agent
[info] Initiated WhiteSource Service
[info] Processing com.typesafe.akka:akka-camel:2.5-SNAPSHOT
java.lang.NoSuchMethodError: sbt.librarymanagement.package$.RichUpdateReport(Lsbt/UpdateReport;)Lsbt/UpdateReport;
	at sbtwhitesource.BaseAction.moduleInfos$1(WhiteSource.scala:164)
	at sbtwhitesource.BaseAction.collectDependencyStructure(WhiteSource.scala:169)
	at sbtwhitesource.BaseAction.sbtwhitesource$BaseAction$$processProject(WhiteSource.scala:146)
	at sbtwhitesource.BaseAction$$anonfun$2.apply(WhiteSource.scala:82)
	at sbtwhitesource.BaseAction$$anonfun$2.apply(WhiteSource.scala:82)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:716)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:692)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toVector(TraversableOnce.scala:269)
	at scala.collection.AbstractIterator.toVector(Iterator.scala:1157)
	at sbtwhitesource.BaseAction.extractProjectInfos(WhiteSource.scala:82)
	at sbtwhitesource.UpdateAction.doExecute(WhiteSource.scala:361)
	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:68)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$5.apply(WhiteSourcePlugin.scala:155)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$5.apply(WhiteSourcePlugin.scala:151)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (akka/*:whitesourceUpdate) java.lang.NoSuchMethodError: sbt.librarymanagement.package$.RichUpdateReport(Lsbt/UpdateReport;)Lsbt/UpdateReport;
akka >
```

**Comment by dwijnand** [comment]
I need to redo some of the sbt plugin migrations I did, because the technique I chose is irresponsible.

In this case what probably happened is [this](https://github.com/typesafehub/migration-manager/blob/0.1.17/sbtplugin/src/main/scala-sbt-0.13/compat.scala#L16) sbt.librarymanagement package object loaded before [this](https://github.com/typesafehub/sbt-whitesource/blob/f18ddea1f11a26b173dde3dcc9073d0154db7e0e/src/main/scala-sbt-0.13/compat.scala#L10) one, causing the runtime error.

Sorry about that, I'll close this ticket when I've rereleased the plugins.

**Comment by dwijnand** [comment]
@raboof Released as https://github.com/typesafehub/sbt-whitesource/releases/tag/v0.1.6

**Comment by raboof** [comment]
Hmm still seems to occur even with 0.1.6: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10046/console (https://github.com/akka/akka/pull/23575/files)

**Comment by raboof** [comment]
weird https://github.com/dwijnand/sbt-compat/blob/master/src/main/scala-sbt-0.13/compat.scala#L34 looks like it should cover this

**Comment by raboof** [comment]
Perhaps because it's not an implicit class but a [normal class](https://github.com/sbt/librarymanagement/blob/1.x/core/src/main/scala/sbt/librarymanagement/RichUpdateReport.scala#L10) with an [implicit conversion](https://github.com/sbt/librarymanagement/blob/53c80f076a5e9ab469037f352a4d68173140e216/core/src/main/scala/sbt/librarymanagement/LibraryManagementSyntax.scala#L9) in sbt.librarymanagement?

**Comment by raboof** [comment]
Hmm I tried making it look more like the 1.0 version but that didn't appear to help (https://github.com/raboof/sbt-compat/commit/ba55c5d892ebccd154ff9feef1c78d34929982f3) - @dwijnand any clue what might be going wrong here?

**Comment by dwijnand** [comment]
Any chance you could give me a reproduction? No need for you to do any (extensive) minimisation, just some starting-point reproduction, with (1) steps, (2) problem, and (3) expectation. Then I can see to undoing this mess-up. Thanks.

**Comment by raboof** [comment]
I created an `sbtWhitesourceIssue20` branch in akka/akka that shows the problem and is slightly minified. 'sbt whitesourceCheckPolicies` on that repo for me produces:
```
[info] Initiated WhiteSource Service
[info] Processing akka-actor:akka-actor:0.1-SNAPSHOT
java.lang.NoSuchMethodError: sbt.librarymanagement.package$.RichUpdateReport(Lsbt/UpdateReport;)Lsbt/UpdateReport;
	at sbtwhitesource.BaseAction.moduleInfos$1(WhiteSource.scala:164)
	at sbtwhitesource.BaseAction.collectDependencyStructure(WhiteSource.scala:169)
	at sbtwhitesource.BaseAction.sbtwhitesource$BaseAction$$processProject(WhiteSource.scala:146)
	at sbtwhitesource.BaseAction$$anonfun$2.apply(WhiteSource.scala:82)
	at sbtwhitesource.BaseAction$$anonfun$2.apply(WhiteSource.scala:82)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:716)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:692)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toVector(TraversableOnce.scala:269)
	at scala.collection.AbstractIterator.toVector(Iterator.scala:1157)
	at sbtwhitesource.BaseAction.extractProjectInfos(WhiteSource.scala:82)
	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:330)
	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:68)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$3.apply(WhiteSourcePlugin.scala:150)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$3.apply(WhiteSourcePlugin.scala:146)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (akka/*:whitesourceCheckPolicies) java.lang.NoSuchMethodError: sbt.librarymanagement.package$.RichUpdateReport(Lsbt/UpdateReport;)Lsbt/UpdateReport;
```

Do you see that as well? It appears it might have something to do with MiMa, removing that plugin appeared to make the problem go away.

**Comment by dwijnand** [comment]
Oh good! Can you see if upgrading to MiMa 0.1.18 fixes it? https://github.com/typesafehub/migration-manager/releases/tag/0.1.18

**Comment by raboof** [comment]
Yes looks like it!

**Comment by dwijnand** [comment]
🕺!
